# Generated by Django 4.2.1 on 2023-06-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institute', models.TextField()),
                ('Programme', models.TextField()),
                ('SeatType', models.TextField()),
                ('Gender', models.TextField()),
                ('OpeningRank', models.IntegerField()),
                ('ClosingRank', models.IntegerField()),
                ('Round', models.IntegerField()),
                ('DualDeg', models.BooleanField()),
            ],
        ),
    ]
