# Generated by Django 4.2.1 on 2023-06-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('josaaanly', '0002_data_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='ClosingRank',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='OpeningRank',
            field=models.TextField(),
        ),
    ]
